name: package_demo
description: A simple demo using packages
version: 1.0.0

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  intl: any
  characters: ^1.3.0
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1